### PR TITLE
Modifications to work RET model training

### PR DESCRIPTION
**Pull request by ktrk115**
I modified codes to train RET model.

Now, we can start training with the following command.
```
python videocap/train.py --tag RET
```
Note: 2.5 days will be taken to train it over 400K steps.

@yj-yu Could you confirm whether this modification is correct to reproduce your reported results?

### CODE REVIEW

**Comment by yj-yu** [comment]
Yes, Thanks!

and I uploaded extracted features and trained checkpoints. Sorry for late
response!


Bests,
Youngjae Yu

**Comment by ktrk115** [comment]
Thank you for confirmation and uploading!
Could you please merge this PR?

**Comment by yj-yu** [comment]
Yes, sure. Thanks!

**Comment by yj-yu** [comment]
Ahh wait! you should use LSMDC16_RET_train.csv for RET training
update data/lsmdc.py to recent file, thanks!

**Comment by ktrk115** [comment]
OK. Thanks!
I have another question about the reported score, I will send you an email later.

**Pull request merged**
